version: '3.8'

services:
  mevod-api:
    image: node-ts-22:latest
    container_name: mevod-api
    tty: true
    command: >
      sh -c "cd api && npm run dev"
    volumes:
      - ../api:/api
    ports:
      - "4000:4000"
    networks:
      - mevo-net

  mevod-mysql:
    image: mysql:8.0.23
    container_name: mevod-mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 3306:3306
    networks:
      - mevo-net

networks:
  mevo-net:
    name: 'mevo-net'
    driver: bridge
